Sylius/SyliusDemo

phpspec.yml.dist, src/AppBundle/EventListener/UserRegistrationListener.php, src/AppBundle/Generator/FlashMessageGeneratorInterface.php, src/AppBundle/Generator/VerificationFlashMessageGenerator.php, src/AppBundle/Resources/config/services.yml, src/AppBundle/Resources/translations/flashes.en.yml, src/AppBundle/Resources/translations/messages.en.yml, src/AppBundle/spec/EventListener/UserRegistrationListenerSpec.php, src/AppBundle/spec/Generator/VerificationFlashMessageGeneratorSpec.php
Unfortunately, flash message is added **after** post event - so I added just new flash message (and modified current) in spite of just modifying the current one.
=> Verification link in flash message

.platform.app.yaml
Related to https://github.com/Sylius/Sylius/pull/7972.
=> Allow woff2 files to be loaded on Platform.sh

app/config/config.yml
allow post api request with simple json object
=> change allow header to content type

.platform/routes.yaml
=> [Platform.sh] Force https usage

.travis.yml, composer.json, composer.lock
- updated **Sylius** to v1.1.0-RC
- updated **SyliusShopApiPlugin** (dev version that allows rc Sylius version, to be changed after next plugin release)
=> Perfect build with updated dependencies

.travis.yml, behat.yml.dist, composer.json, composer.lock
Based on https://github.com/Sylius/SyliusDemo/pull/26
Regarding excluded features see: https://github.com/Sylius/SyliusDemo/issues/29
=> Run Sylius tests on SyliusDemo

app/AppKernel.php, app/TestAppKernel.php, src/AppBundle/DependencyInjection/AppExtension.php, src/AppBundle/DependencyInjection/Configuration.php, src/AppBundle/EventListener/AdminListener.php, src/AppBundle/EventListener/ChannelListener.php, src/AppBundle/EventListener/UserRegistrationListener.php, src/AppBundle/Generator/FlashMessageGeneratorInterface.php, src/AppBundle/Generator/VerificationFlashMessageGenerator.php, src/AppBundle/spec/EventListener/AdminListenerSpec.php, src/AppBundle/spec/EventListener/UserRegistrationListenerSpec.php, src/AppBundle/spec/Generator/VerificationFlashMessageGeneratorSpec.php
- no author blocks - https://github.com/Sylius/Sylius/pull/8882
- PHP7 typehints - https://github.com/Sylius/Sylius/issues/8425
=> Follow Sylius conventions and CS

behat.yml.dist, composer.json, features/displaying_verification_link_after_registration.feature, features/preventing_channel_addition.feature, features/preventing_default_administrator_deletion.feature, features/preventing_default_administrator_edition.feature, tests/Behat/Context/Ui/Admin/ManagingAdministratorsContext.php, tests/Behat/Context/Ui/Admin/ManagingChannelsContext.php, tests/Behat/Context/Ui/Shop/RegistrationContext.php, tests/Behat/Resources/config/services.xml, tests/Behat/Resources/config/suites.yml
This is the first step to make *SyliusDemo* more reliable - https://github.com/Sylius/SyliusDemo/issues/29. Features that need to be described/tested:
=> Describe customized behavior

.platform.app.yaml
It appears that composer scripts do not work on platform.sh
=> [Platform.sh] Fix demo reload

templates/bundles/SyliusAdminBundle/layout.html.twig
=> Add Sylius logo

templates/base.html.twig
=> Add Google Analytics code

yarn.lock
=> [Maintenance] Yarn upgrade

package.json, yarn.lock
After merge https://github.com/Sylius/Sylius/pull/10903
=> [Maintenance] Add slick-carousel to package.json

config/packages/prod/swiftmailer.yaml
I want to control mailing possibilities with env, rather than having it hardcoded.
=> [Maintenance] Remove forced mail disabling

.travis.yml, composer.json, composer.lock, config/bundles.php, config/packages/_sylius.yaml, config/routes.yaml, src/Migrations/Version20191212133950.php, symfony.lock
=> Add SyliusCmsPlugin to demo 

src/Migrations/Version20191212133950.php
Fix for : https://github.com/Sylius/SyliusDemo/pull/105/files#diff-beb9b616bbaa1d9a30040bad56da18ceR72
=> Remove redundant migrations

templates/_version_switcher.html.twig
=> Rename versions in version switcher on master demo

templates/_version_switcher.html.twig
=> Rename stable and master versions in version switcher on stable demo

templates/bundles/SyliusShopBundle/Login/_form.html.twig, templates/bundles/SyliusUiBundle/Security/_login.html.twig
=> Add test credentials above login forms on stable branch

composer.lock, templates/bundles/SyliusShopBundle/Login/_form.html.twig, templates/bundles/SyliusUiBundle/Security/_login.html.twig
=> Add test credentials above login forms on master branch

config/bundles.php
According to https://github.com/Sylius/Sylius/pull/10977
=> Remove SonataIntlBundle

composer.lock, templates/bundles/SyliusShopBundle/layout.html.twig
See https://github.com/Sylius/Sylius/pull/11012/files#diff-19c42e8bd7033aac31b850a202b103ceR45
=> Fix template after menu taxon introduction

src/Migrations/Version20200202104152.php
In Sylius we added new property on shipment entity - date when admin shipped a shipment (shippedAt)
here I added missing migration related with this PR Sylius/Sylius#11089
=> [Migrations] Shipped at date

composer.json, composer.lock, src/Migrations/Version20200220074850.php
I propose to lock on specific patch version of **CmsPlugin** to avoid such unexpected problems in the future 🖖
=> [Fix deploy] Update and lock CmsPlugin

templates/bundles/SyliusAdminBundle/AdminUser/_form.html.twig
=> [AdminUser] Bring back Admin avatar

templates/_infoBox.html.twig
=> Add link to Swagger UI to info box on homepage

config/packages/security.yaml
Waiting for https://github.com/Sylius/Sylius/pull/11397
=> Update security config after changes in Sylius

composer.lock, config/packages/doctrine.yaml, symfony.lock
Missing of this library causes 500 in Admin panel 💥
=> [HOTFIX] Update dependencies

composer.lock, config/packages/doctrine.yaml, symfony.lock
Reverts Sylius/SyliusDemo#137
Not needed since https://github.com/Sylius/Sylius/pull/11465
=> Revert "[HOTFIX] Update dependencies"

src/Migrations/Version20200309172908.php
Duplicated migration from https://github.com/Sylius/Sylius/pull/11241/
=> [Migration] Add missing migration

config/packages/fos_rest.yaml, config/packages/security.yaml
After https://github.com/Sylius/Sylius/pull/12257
=> [Maintenance] Adjust configs after change new-api to api/v2

composer.json, composer.lock
=> Add missing dotenv

composer.json, composer.lock, config/packages/_sylius.yaml, src/EventListener/ChannelListener.php, symfony.lock
=> [Maintenance] Turn on unified api

README.md
Copied from https://github.com/Sylius/Sylius
=> Update community support channels

.github/workflows/build.yml, package.json
After https://github.com/Sylius/Sylius/pull/13488
=> [Maintenance] Update gulp-sass version

.github/workflows/build.yml, .gitignore, .php_cs.dist, composer.json, composer.lock, config/bundles.php, config/packages/_sylius.yaml, config/packages/fos_ckeditor.yaml, config/packages/twig.yaml, config/routes.yaml, symfony.lock, yarn.lock
Our demo is down due to installation of webpack, which is result of cms plugin. I've decided to remove it, as it wasn't even used in UI. 
We may properly add it later
=> [Maintenance] Remove BitBag CMS to bring life to our demo

package.json
According to: https://github.com/Sylius/Sylius/blob/master/UPGRADE-1.12.md
=> [JS] Bump dependencies required by newest Sylius master

templates/Blocks/_infoBox.html.twig
=> [UI] Smaller info box

.github/workflows/build.yml, composer.json, composer.lock
=> [Maintenance][Composer] Update Sylius dependency definition and cleanup

config/packages/security.yaml
Updated `security.yaml` to support the newest changes on OS
=> [Security] Updated security.yaml

config/packages/framework.yaml, config/packages/webpack_encore.yaml
=> [Maintenace] Add Webpack configuration

composer.json, composer.lock, config/bundles.php, config/packages/_sylius.yaml, src/Entity/Channel/Channel.php, src/Entity/Channel/ChannelPricing.php
=> Add PriceHistory plugin

config/packages/_sylius.yaml
=> Import config for PriceHistoryPlugin

config/routes/sylius_admin.yaml, symfony.lock
=> Load PriceHistory routes
